#!/usr/bin/env bash
# ==============================================================================
# deploy/fetch-oci-vault-secrets.sh
# Prompts for production secrets and writes them to /etc/forsic/.env (mode 600)
# Secrets are NEVER stored in Git — only on the server in /etc/forsic/
#
# Run once before first deployment. Re-run only when rotating secrets.
#
# Usage:
#   sudo bash deploy/fetch-oci-vault-secrets.sh
# ==============================================================================
set -euo pipefail

ENV_DIR="/etc/forsic"
ENV_FILE="${ENV_DIR}/.env"

echo "======================================================"
echo " FORSIC — Production Secrets Setup"
echo " Secrets will be stored at: ${ENV_FILE}"
echo " (mode 600 — only root can read)"
echo "======================================================"
echo ""
echo " Generate strong secrets on your machine:"
echo "   Passwords:  openssl rand -base64 32"
echo "   JWT_SECRET: openssl rand -hex 32"
echo "   KMS_KEY:    openssl rand -base64 32"
echo ""
echo " Enter each secret below (input is hidden):"
echo ""

# ---- Read secrets interactively (hidden input) ----
read -rsp "  POSTGRES_PASSWORD     : " POSTGRES_PASSWORD;     echo
read -rsp "  REDIS_PASSWORD        : " REDIS_PASSWORD;        echo
read -rsp "  MINIO_ROOT_PASSWORD   : " MINIO_PASSWORD;        echo
read -rsp "  JWT_SECRET            : " JWT_SECRET;            echo
read -rsp "  KMS_MASTER_KEY        : " KMS_MASTER_KEY;        echo
read -rsp "  PKI_KEYSTORE_PASSWORD : " PKI_KEYSTORE_PASSWORD; echo

echo ""

# ---- Validate none are empty ----
for VAR_NAME in POSTGRES_PASSWORD REDIS_PASSWORD MINIO_PASSWORD JWT_SECRET KMS_MASTER_KEY PKI_KEYSTORE_PASSWORD; do
  VAL="${!VAR_NAME}"
  if [[ -z "${VAL}" ]]; then
    echo "[ERROR] ${VAR_NAME} cannot be empty."
    exit 1
  fi
done

# ---- Create secure directory ----
mkdir -p "${ENV_DIR}"
chmod 700 "${ENV_DIR}"

# ---- Write env file ----
cat > "${ENV_FILE}" <<EOF
# =======================================================
# FORSIC Production Secrets
# Auto-generated by fetch-oci-vault-secrets.sh
# DO NOT EDIT MANUALLY — re-run the script to update.
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# =======================================================

SPRING_PROFILES_ACTIVE=prod

POSTGRES_DB=secure_documents_db
POSTGRES_USER=sih190_user
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

SPRING_DATA_REDIS_HOST=redis
SPRING_DATA_REDIS_PORT=6379
REDIS_PASSWORD=${REDIS_PASSWORD}

MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
S3_BUCKET_NAME=sih190-evidence-vault
S3_QUARANTINE_BUCKET_NAME=sih190-quarantine-vault

CLAMAV_ENABLED=true
CLAMAV_FAIL_CLOSED=true
CLAMAV_HOST=clamav
CLAMAV_PORT=3310

ELASTICSEARCH_URL=http://elasticsearch:9200
ELASTICSEARCH_ENABLED=true

JWT_SECRET=${JWT_SECRET}
JWT_AUDIENCE=sih190-api
KMS_MASTER_KEY=${KMS_MASTER_KEY}
PKI_KEYSTORE_PASSWORD=${PKI_KEYSTORE_PASSWORD}

SERVER_PORT=8080
FRONTEND_PORT=3000
EOF

# ---- Lock down file permissions ----
chmod 600 "${ENV_FILE}"
chown root:root "${ENV_FILE}"

echo "[OK] Secrets written to ${ENV_FILE} (mode 600, owner root)"
echo ""
echo "======================================================"
echo " Done! Next step:"
echo "   sudo bash deploy/deploy.sh"
echo "======================================================"
